### PR TITLE
SVG sketch export: grouping areas, lines and points by type

### PR DESCRIPTION
**Pull request by rsevero**
SVG points, lines and areas are exported in all together, without distinction of point, line or area type.

This pull request grolups points, lines and areas by type.

### CODE REVIEW

**Comment by marcocorvi** [comment]
repeat for svg-walls export ?

**Comment by rsevero** [comment]
I can try to do it certainly. 

Can you explain what is the rationale for svg-walls? I see it already does some kind of object separation.

Would you like that inside each class already used at svg-walls (detail_shp, detail_sym, walls_shp, walls_sym, etc) I repeat the kind of separation I did on SVG export?

**Comment by marcocorvi** [comment]
svg roundtrip:
a clumsy solution to map drafting,
good only for us people

**Comment by rsevero** [comment]
Ok.

So inside each existing group: detail_shp, detail_sym, walls_shp, walls_sym, etc, I should further aggregate symbol types. Is that it?

**Comment by marcocorvi** [comment]
i dont remember exactly how it works.
should check the docs, 
or, easier, try an example with 1 point,1 line and 1 area and see where they go.
svg is text file

**Comment by rsevero** [comment]
I decided not to mess with SVG Walls as the aggregation of paths is very specific: I am afraid nay change I made might be undesirable to the users of this option.

Just commited a few improvements for SVG export.

**Comment by marcocorvi** [comment]
No.
(1) i added a setting to choose whether to group items by the type or not
(2) with SvgWalls everything is in  writePaths with a big TODO

**Pull request merged**
