### PR TITLE
Strings check

### PR DESCRIPTION
**Pull request by rsevero**
Created _strings_check.pl_ to be used on a translation file just before a translator sends an updated version of the translation file. It currently checks for:

1. translations that have no original (EN) version
2. copied translations for original entries without an appropriate 'copyable' attribute
3. commented translations for uncommented original entries
4. translation for original entries with 'translatable=false'
5. non commented translations for commented originals
6. missing translations
7. bad formats
8. invalid xml files

Please let me know if there are any other tests you would like to be done on translation files.

For that I created a _topostrings.pm_ perl package where I moved functions used both by _strings_check.pl_ and _strings_prepare.pl_

_strings_prepare.pl_ has been updated to remove the 'copyable' attribute from translated files to reduce their sizes.

### CODE REVIEW

**Comment by marcocorvi** [comment]
thanks

On Fri, Feb 17, 2023, 3:37 PM Rodrigo Severo ***@***.***>
wrote:

> Created *strings_check.pl <http://strings_check.pl>* to be used on a
> translation file just before a translator sends an updated version of the
> translation file. It currently checks for:
>
>    1. translations that have no original (EN) version
>    2. copied translations for original entries without an appropriate
>    'copyable' attribute
>    3. commented translations for uncommented original entries
>    4. translation for original entries with 'translatable=false'
>    5. non commented translations for commented originals
>    6. missing translations
>    7. bad formats
>
> For that I created a *topostrings.pm <http://topostrings.pm>* perl
> package where I moved functions used both by *strings_check.pl
> <http://strings_check.pl>* and *strings_prepare.pl
> <http://strings_prepare.pl>*
>
> *strings_prepare.pl <http://strings_prepare.pl>* has been updated to
> remove the 'copyable' attribute from translated files to reduce their sizes.
>
this is not good because lint signals error if they are missing.

**Comment by rsevero** [comment]
------- Original Message -------
On Friday, February 17th, 2023 at 12:28 PM, marco corvi ***@***.***> wrote:

> thanks
>> *strings_prepare.pl <http://strings_prepare.pl>* has been updated to
>> remove the 'copyable' attribute from translated files to reduce their sizes.
>>
>
> this is not good because lint signals error if they are missing.

Feature removed from strings_prepare.pl.

RodrigoMessage ID: ***@***.***>

>

**Comment by marcocorvi** [comment]
"walls" is translated is some strings, untranslated in others.
i think the same term should be used consistently otherwise the user 
may be confused.

**Comment by rsevero** [comment]
Fixed.

------- Original Message -------

**Pull request merged**
