### PR TITLE
minor improvements in res/values xml files

### PR DESCRIPTION
**Pull request by rsevero**
Minor improvements for res/values xml files to better work with new strings_update.pl

Only the duplicated entry removal in strings.xml is really necessary. The other ones are comestic.

### CODE REVIEW

**Comment by marcocorvi** [comment]
these change to default files are not needed

**Comment by rsevero** [comment]
The duplicated entry removal is necessary to use the new version of strings_update.pl just merged. Otherwise I agree it is not needed.

**Comment by marcocorvi** [comment]
please explain.
thanks

**Comment by rsevero** [comment]
The last version of strings_update.pl I sent can process the 3 translation files: strings.xml, array.xml and plurals.xml.

With it, if you want, you can automatically update all translations so they have the appropriate TODOs, UNUSEDs etc. The only thing missing is a simple script that automatically calls strings_update.pl for the 3 translation files of each language.

With it it will be really easy to keep all translation files updated with all TODOs, UNUSEDs, etc.

In strings_update.pl, as I need to use the "name" attribute as the key to relate EN strings with the translated ones, I have to check if there is only one entry with each name in each file and I have to consider even the commented entries, I can't disregard them just because they are commented.

When doing a regular XML processing comments are simply ignored but, as in Topodroids translation system the commented entries have meaning, the processing strings_update does starts with a check looking for name duplicated entries, both in the original EN file and in the translation file. This is necessary so strings_update knows which entry is related to which entry.

The update I sent for the original EN files removes the single duplication I found in strings.xml. This change is necessary to use strings_update.pl with it.

The other changes: including TODOs comments in the beggining of each EN file is just a comestic change to guarantee that all translated files, after being processed be strings_update.pl, have that same comment in the beggining. This change is not necessary.
------- Original Message -------

**Comment by marcocorvi** [comment]
On Mon, Jan 30, 2023, 1:11 PM Rodrigo Severo ***@***.***>
wrote:

> The last version of strings_update.pl I sent can process the 3
> translation files: strings.xml, array.xml and plurals.xml.
>
> With it, if you want, you can automatically update all translations so
> they have the appropriate TODOs, UNUSEDs etc. The only thing missing is a
> simple script that automatically calls strings_update.pl for the 3
> translation files of each language.
>

i consider the script a tool for translation maintainers.
i prefer to check every change to the source files.
translation files are responsability of the maintainer, and i only add TODO
strings or comment with UNUSED (i use a vi macro),  when i change the
english file.

>
> With it it will be really easy to keep all translation files updated with
> all TODOs, UNUSEDs, etc.
>
> In strings_update.pl, as I need to use the "name" attribute as the key to
> relate EN strings with the translated ones, I have to check if there is
> only one entry with each name in each file and I have to consider even the
> commented entries, I can't disregard them just because they are commented.
>
> When doing a regular XML processing comments are simply ignored but, as in
> Topodroids translation system the commented entries have meaning, the
> processing strings_update does starts with a check looking for name
> duplicated entries, both in the original EN file and in the translation
> file. This is necessary so strings_update knows which entry is related to
> which entry.
>
> The update I sent for the original EN files removes the single duplication
> I found in strings.xml. This change is necessary to use strings_update.pl
> with it.
>

i agree: names should not be duplicated in the english files.
i will check that.


> The other changes: including TODOs comments in the beggining of each EN
> file is just a comestic change to guarantee that all translated files,
> after being processed be strings_update.pl, have that same comment in the
> beggining. This change is not necessary.
>

yes, this is not necessary.
the script can add it to the translation files if needed.

------- Original Message -------

**Comment by rsevero** [comment]
------- Original Message -------
On Monday, January 30th, 2023 at 9:29 AM, marco corvi ***@***.***> wrote:

> On Mon, Jan 30, 2023, 1:11 PM Rodrigo Severo ***@***.***>
> wrote:
>
>> The last version of strings_update.pl I sent can process the 3
>> translation files: strings.xml, array.xml and plurals.xml.
>>
>> With it, if you want, you can automatically update all translations so
>> they have the appropriate TODOs, UNUSEDs etc. The only thing missing is a
>> simple script that automatically calls strings_update.pl for the 3
>> translation files of each language.
>>
>
> i consider the script a tool for translation maintainers.
> i prefer to check every change to the source files.
> translation files are responsability of the maintainer, and i only add TODO
> strings or comment with UNUSED (i use a vi macro), when i change the
>
> english file.

Yes. I know. But it's a huge work to manually add the TODOs and UNUSEDs in the translation files. By you or by the translators. This new strings_update.pl does this part automatically saving a lot of work.

Calling strings_update.pl can certainly be left to the translators but it seems to me a lot more error prone as several people with varying levels of computer expertise will have to learn how to use it and install the necessary dependencies.

Having a script that automatically applies the original EN file updates to all translation files (by calling strings_update.pl on all of them) is really easy and quick.

But you know way better than me the best way to manage a project the size and complexity of Topodroid. Use my contribution the way it seems better to you.

**Comment by marcocorvi** [comment]
On Mon, Jan 30, 2023 at 2:06 PM Rodrigo Severo ***@***.***>
wrote:

> ------- Original Message -------
> On Monday, January 30th, 2023 at 9:29 AM, marco corvi ***@***.***> wrote:
>
> > On Mon, Jan 30, 2023, 1:11 PM Rodrigo Severo ***@***.***>
> > wrote:
> >
> >> The last version of strings_update.pl I sent can process the 3
> >> translation files: strings.xml, array.xml and plurals.xml.
> >>
> >> With it, if you want, you can automatically update all translations so
> >> they have the appropriate TODOs, UNUSEDs etc. The only thing missing is
> a
> >> simple script that automatically calls strings_update.pl for the 3
> >> translation files of each language.
> >>
> >
> > i consider the script a tool for translation maintainers.
> > i prefer to check every change to the source files.
> > translation files are responsability of the maintainer, and i only add
> TODO
> > strings or comment with UNUSED (i use a vi macro), when i change the
> >
> > english file.
>
> Yes. I know. But it's a huge work to manually add the TODOs and UNUSEDs in
> the translation files. By you or by the translators. This new
> strings_update.pl does this part automatically saving a lot of work.
>

not much.
usually only a few (2 or 3) strings, if any, are added or changed at a
update.

>
> Calling strings_update.pl can certainly be left to the translators but it
> seems to me a lot more error prone as several people with varying levels of
> computer expertise will have to learn how to use it and install the
> necessary dependencies.


if one has the experteeses to use it, he can use it,
otherwise he will find other ways to do the job.


>


> Having a script that automatically applies the original EN file updates to
> all translation files (by calling strings_update.pl on all of them) is
> really easy and quick.
>
yes, one line:
for x in ... : do ./strings_update.pl .... ; done
[replace ellipses with proper expressions]

>
> But you know way better than me the best way to manage a project the size
> and complexity of Topodroid. Use my contribution the way it seems better to
> you.
> Message ID: ***@***.***>
>

probably my way is not the best, but topodroid is a small-size project,
fortunately.

**Comment by rsevero** [comment]
------- Original Message -------
On Monday, January 30th, 2023 at 10:49 AM, marco corvi ***@***.***> wrote:

> On Mon, Jan 30, 2023 at 2:06 PM Rodrigo Severo ***@***.***>
> wrote:
>
>> ------- Original Message -------
>> On Monday, January 30th, 2023 at 9:29 AM, marco corvi ***@***.***> wrote:
>>
>> > On Mon, Jan 30, 2023, 1:11 PM Rodrigo Severo ***@***.***>
>> > wrote:
>> >
>> > i consider the script a tool for translation maintainers.
>> > i prefer to check every change to the source files.
>> > translation files are responsability of the maintainer, and i only add
>> TODO
>> > strings or comment with UNUSED (i use a vi macro), when i change the
>> >
>> > english file.
>>
>> Yes. I know. But it's a huge work to manually add the TODOs and UNUSEDs in
>> the translation files. By you or by the translators. This new
>> strings_update.pl does this part automatically saving a lot of work.
>>
>
> not much.
> usually only a few (2 or 3) strings, if any, are added or changed at a
>
> update.

My mistake. I understood that you stopped updating all translation files with the relevant TODOs and UNUSEDs because it felt as too much work to be done manually. That's the reason I decided to write this last script so this part of the work could be done automatically.

>> Calling strings_update.pl can certainly be left to the translators but it
>> seems to me a lot more error prone as several people with varying levels of
>> computer expertise will have to learn how to use it and install the
>> necessary dependencies.
>
> if one has the experteeses to use it, he can use it,
>
> otherwise he will find other ways to do the job.

During this last effort to update the portuguese translation, after translationg all TODOs that were already in the portuguese file (which I though were all that needed translation) you told me that there were 200 more that weren't even included in the portuguese translation file.

I almost gave up when I though I would have to manually copy and past one by one from the EN file to the PT file. That was my incentive to write the first version of strings_update.pl

I wonder if other translators won't be unnecessarily discouraged getting the job done by the need of installing whatever tool or manually doing the identification and copy/pasting of the necessary TODOs.

**Comment by marcocorvi** [comment]
On Mon, Jan 30, 2023, 5:58 PM Rodrigo Severo ***@***.***>
wrote:

> ------- Original Message -------
> On Monday, January 30th, 2023 at 10:49 AM, marco corvi ***@***.***> wrote:
>
> > On Mon, Jan 30, 2023 at 2:06 PM Rodrigo Severo ***@***.***>
> > wrote:
> >
> >> ------- Original Message -------
> >> On Monday, January 30th, 2023 at 9:29 AM, marco corvi ***@***.***>
> wrote:
> >>
> >> > On Mon, Jan 30, 2023, 1:11 PM Rodrigo Severo ***@***.***>
> >> > wrote:
> >> >
> >> > i consider the script a tool for translation maintainers.
> >> > i prefer to check every change to the source files.
> >> > translation files are responsability of the maintainer, and i only add
> >> TODO
> >> > strings or comment with UNUSED (i use a vi macro), when i change the
> >> >
> >> > english file.
> >>
> >> Yes. I know. But it's a huge work to manually add the TODOs and UNUSEDs
> in
> >> the translation files. By you or by the translators. This new
> >> strings_update.pl does this part automatically saving a lot of work.
> >>
> >
> > not much.
> > usually only a few (2 or 3) strings, if any, are added or changed at a
> >
> > update.
>
> My mistake. I understood that you stopped updating all translation files
> with the relevant TODOs and UNUSEDs because it felt as too much work to be
> done manually. That's the reason I decided to write this last script so
> this part of the work could be done automatically.
>
> >> Calling strings_update.pl can certainly be left to the translators but
> it
> >> seems to me a lot more error prone as several people with varying
> levels of
> >> computer expertise will have to learn how to use it and install the
> >> necessary dependencies.
> >
> > if one has the experteeses to use it, he can use it,
> >
> > otherwise he will find other ways to do the job.
>
> During this last effort to update the portuguese translation, after
> translationg all TODOs that were already in the portuguese file (which I
> though were all that needed translation) you told me that there were 200
> more that weren't even included in the portuguese translation file.
>
> I almost gave up when I though I would have to manually copy and past one
> by one from the EN file to the PT file. That was my incentive to write the
> first version of strings_update.p <http://strings_update.pl>l


>
> I wonder if other translators won't be unnecessarily discouraged getting
> the job done by the need of installing whatever tool or manually doing the
> identification and copy/pasting of the necessary TODOs.
>

i agree.
having to copy and translate hundreds strings can be discouraging and one
might not even start to do it.
having to resolve dependencies to run a script that automates part of the
job, can also be discouraging.
i do not know if there is a simple solution, ...
since strings are aligned bcompare could be useful: one can
easily copy strings from one file to the other, edit in place, and so on.

**Comment by rsevero** [comment]
------- Original Message -------
On Monday, January 30th, 2023 at 3:43 PM, marco corvi ***@***.***> wrote:

> On Mon, Jan 30, 2023, 5:58 PM Rodrigo Severo ***@***.***>
> wrote:
>
>> ------- Original Message -------
>> On Monday, January 30th, 2023 at 10:49 AM, marco corvi ***@***.***> wrote:
>>
>> > On Mon, Jan 30, 2023 at 2:06 PM Rodrigo Severo ***@***.***>
>> > wrote:
>> >
>> >> ------- Original Message -------
>> >> On Monday, January 30th, 2023 at 9:29 AM, marco corvi ***@***.***>
>> wrote:
>> >>
>>
>> During this last effort to update the portuguese translation, after
>> translationg all TODOs that were already in the portuguese file (which I
>> though were all that needed translation) you told me that there were 200
>> more that weren't even included in the portuguese translation file.
>>
>> I almost gave up when I though I would have to manually copy and past one
>> by one from the EN file to the PT file. That was my incentive to write the
>> first version of strings_update.p <http://strings_update.pl>l
>
>>
>> I wonder if other translators won't be unnecessarily discouraged getting
>> the job done by the need of installing whatever tool or manually doing the
>> identification and copy/pasting of the necessary TODOs.
>>
>
> i agree.
> having to copy and translate hundreds strings can be discouraging and one
> might not even start to do it.
> having to resolve dependencies to run a script that automates part of the
> job, can also be discouraging.
> i do not know if there is a simple solution, ...
> since strings are aligned bcompare could be useful: one can
>
> easily copy strings from one file to the other, edit in place, and so on.

Or you could automate the TODOs and UNUSEDs inclusion on all translations using this last version of strings_update.pl ;)

**Comment by marcocorvi** [comment]
you should update the pt files.

the script has a few problems (besides dependencies which can hold back its
usage from some people):

it does not check args (this is only a minor annoyance)

it does not fix formats (this may cause app crash)

it writes a new file in a resource folder -  user can blindly move the new
file over the old one, but then the script could just overwrite the old file

**Comment by rsevero** [comment]
------- Original Message -------
On Tuesday, January 31st, 2023 at 4:26 AM, marco corvi ***@***.***> wrote:

> you should update the pt files.

Doing that.

One doubt: the strings with 'translatable="false"' should be present in the translated files but not translated or should they not be present at all on the translated files?

> the script has a few problems (besides dependencies which can hold back its
>
> usage from some people):

Yes, I am aware of that but I decided to have some extra dependencies because:

- With them (specially XML::LibXML) I managed to write one single script that deals with the 3 translation files and easily deal with any and all XML possibilities;
- I didn't write it imaging it would be used by the translators themselves. I imagined it would be used by you automatically updating all translation files all the time so only one person would need to deal with its dependencies.

> it does not check args (this is only a minor annoyance)

Just fixed it.

> it does not fix formats (this may cause app crash)

I don't understand what you mean. Can you please explain?

> it writes a new file in a resource folder - user can blindly move the new
>
> file over the old one, but then the script could just overwrite the old file

I was exactly worried about users using it blindly and eventually overwriting files by mistake. This is why I decided to write a new file and not overwrite the original one. Do you believe there is a better way to go?Message ID: ***@***.***>

>

**Comment by marcocorvi** [comment]
On Tue, Jan 31, 2023, 11:23 AM Rodrigo Severo ***@***.***>
wrote:

> ------- Original Message -------
> On Tuesday, January 31st, 2023 at 4:26 AM, marco corvi ***@***.***> wrote:
>
> > you should update the pt files.
>
> Doing that.
>
> One doubt: the strings with 'translatable="false"' should be present in
> the translated files but not translated or should they not be present at
> all on the translated files?
>

it does not matter.
they can be commented or missing.
it is an error only if they are translated.

>
> > the script has a few problems (besides dependencies which can hold back
> its
> >
> > usage from some people):
>
> Yes, I am aware of that but I decided to have some extra dependencies
> because:
>
> - With them (specially XML::LibXML) I managed to write one single script
> that deals with the 3 translation files and easily deal with any and all
> XML possibilities;
> - I didn't write it imaging it would be used by the translators
> themselves. I imagined it would be used by you automatically updating all
> translation files all the time so only one person would need to deal with
> its dependencies.
>

i prefer not to mess with translation files because i do not know most of
the languages.
therefore i limit myself to add TODO commented strings, on comment with
UNUSED.

>
> > it does not check args (this is only a minor annoyance)
>
> Just fixed it.
>
> > it does not fix formats (this may cause app crash)
>
> I don't understand what you mean. Can you please explain?
>

formats contain %N$X where N is a number and X a C var-format.
if the format is wrong when the app tries to use it, the app may crash.

>
> > it writes a new file in a resource folder - user can blindly move the new
> >
> > file over the old one, but then the script could just overwrite the old
> file
>
> I was exactly worried about users using it blindly and eventually
> overwriting files by mistake. This is why I decided to write a new file and
> not overwrite the original one. Do you believe there is a better way to go?


write to stdout (by default) and user can use shell redirection, or take
output filename.

**Comment by marcocorvi** [comment]
On Tue, Jan 31, 2023 at 12:10 PM Rodrigo Severo ***@***.***>
wrote:

> ------- Original Message -------
> On Tuesday, January 31st, 2023 at 7:40 AM, marco corvi ***@***.***> wrote:
>
> > On Tue, Jan 31, 2023, 11:23 AM Rodrigo Severo ***@***.***>
> > wrote:
> >
> >> ------- Original Message -------
> >> On Tuesday, January 31st, 2023 at 4:26 AM, marco corvi ***@***.***>
> wrote:
> >>
> >> > you should update the pt files.
> >>
> >> Doing that.
> >>
> >> One doubt: the strings with 'translatable="false"' should be present in
> >> the translated files but not translated or should they not be present at
> >> all on the translated files?
> >>
> >
> > it does not matter.
> > they can be commented or missing.
> >
> > it is an error only if they are translated.
>
> Ok. I will keep removing 'translatable="false"' from the translation
> files. Seems safer as this way it's impossible for the translator to
> translate something that is not there at all.
>
> >> > the script has a few problems (besides dependencies which can hold
> back
> >> its
> >> >
> >> > usage from some people):
> >>
> >> Yes, I am aware of that but I decided to have some extra dependencies
> >> because:
> >>
> >> - With them (specially XML::LibXML) I managed to write one single script
> >> that deals with the 3 translation files and easily deal with any and all
> >> XML possibilities;
> >> - I didn't write it imaging it would be used by the translators
> >> themselves. I imagined it would be used by you automatically updating
> all
> >> translation files all the time so only one person would need to deal
> with
> >> its dependencies.
> >>
> >
> > i prefer not to mess with translation files because i do not know most of
> > the languages.
> > therefore i limit myself to add TODO commented strings, on comment with
> >
> > UNUSED.
>
> Do you understand that this is exactly what 'strings_update.pl' does? It
> adds TODO and applies UNUSED comments. The idea is doing automatically what
> you use to do by hand.
>

yes.
maybe i will test it when there is a chance.

it is a script for someone who wants to do a new translation or pick up an
old translation and update it.
by the way it should work also if the translated file does not exist yet.

**Comment by marcocorvi** [comment]
if a fornat is translated but it contains format mistakes, it should not be
copied to the new file.
otherwise the mistake will not be fixed.

therefore it is important that the update script detects bad formats, and
replaces them with TODO.

there is another issue: copied strings.
there are strings that coincide in english and in some translations, eg
"photo" is english and french as well.
but there are strings that differ and need to be translated.
these false translation should be recognized and marked TODO.

since this is language dependent ("photo" must be translated in italian), i
added the attribute copyable to the default string file.
this attribute lists the languages for which the string is written as in
english.
the attribute does not need to appear in the translation files.

**Comment by rsevero** [comment]
------- Original Message -------
On Tuesday, January 31st, 2023 at 9:17 AM, marco corvi ***@***.***> wrote:

> if a fornat is translated but it contains format mistakes, it should not be
> copied to the new file.
> otherwise the mistake will not be fixed.
>
> therefore it is important that the update script detects bad formats, and
> replaces them with TODO.
>
> there is another issue: copied strings.
> there are strings that coincide in english and in some translations, eg
> "photo" is english and french as well.
> but there are strings that differ and need to be translated.
> these false translation should be recognized and marked TODO.
>
> since this is language dependent ("photo" must be translated in italian), i
> added the attribute copyable to the default string file.
> this attribute lists the languages for which the string is written as in
> english.
>
> the attribute does not need to appear in the translation files.

I have this list of TODOs for the next version of strings_prepare.pl:

- Create translation file for new language
- Check formats and replace wrong ones with TODOs
- Deal 'copyable' strings

I have some doubts:

- When I find a wrong format, what text content should I place inside the new TODO? The translated wrong one or should I throw it away and just include the original correct english one? Or should I append one to the other using something like a vertical bar to separate them?
- About the 'copyable' strings: if I am preparing a translation file for a language where a string is copyable, should this string not appear at all in the translated file of this same language if the translated text content is the same as the original english one?
- For other languages, not listed as copyable in a string, if the text content is the same as the original english one, it should be marked as TODO, right?

**Comment by marcocorvi** [comment]
On Tue, Jan 31, 2023, 2:07 PM Rodrigo Severo ***@***.***>
wrote:

> ------- Original Message -------
> On Tuesday, January 31st, 2023 at 9:17 AM, marco corvi ***@***.***> wrote:
>
> > if a fornat is translated but it contains format mistakes, it should not
> be
> > copied to the new file.
> > otherwise the mistake will not be fixed.
> >
> > therefore it is important that the update script detects bad formats, and
> > replaces them with TODO.
> >
> > there is another issue: copied strings.
> > there are strings that coincide in english and in some translations, eg
> > "photo" is english and french as well.
> > but there are strings that differ and need to be translated.
> > these false translation should be recognized and marked TODO.
> >
> > since this is language dependent ("photo" must be translated in
> italian), i
> > added the attribute copyable to the default string file.
> > this attribute lists the languages for which the string is written as in
> > english.
> >
> > the attribute does not need to appear in the translation files.
>
> I have this list of TODOs for the next version of strings_prepare.pl:
>
> - Create translation file for new language
> - Check formats and replace wrong ones with TODOs
> - Deal 'copyable' strings
>

the second is the most important


> I have some doubts:
>
> - When I find a wrong format, what text content should I place inside the
> new TODO? The translated wrong one or should I throw it away and just
> include the original correct english one? Or should I append one to the
> other using something like a vertical bar to separate them?
>

the current english format, of course.
the bad format is bad, and it is better to do it all over.

bad formats are rare, fortunately.

- About the 'copyable' strings: if I am preparing a translation file for a
> language where a string is copyable, should this string not appear at all
> in the translated file of this same language if the translated text content
> is the same as the original english one?
>

copyable strings *should* be copied otherwise lint signals non-translated
(sig!).

- For other languages, not listed as copyable in a string, if the text
> content is the same as the original english one, it should be marked as
> TODO, right?


no.

the decision whether a string is copyable or not is up to the translation
maintainer, who is the person that knows the translation language.

therefore it is *acceptable* that a string that is not marked copyable is
copied.
let's say it is a warning, not an error.

adding to mathias' mail:
there are a number of errors that come up in the build:
- unescaped chars (mostly apostrophy)
- unclosed string elements (very common to forget to remove end-of-comment
- extra space between < and string
- others that i dont remember.

usually these are a few, and i fix them (otherwise i cannot build the app).

unicode issues are caugth by lint.
it is also smart enough to catch some misspelling :-)
however these are  sub-critical (no crash, just strange message)

**Comment by rsevero** [comment]
------- Original Message -------
On Tuesday, January 31st, 2023 at 10:30 AM, Matthias Keller ***@***.***> wrote:

>> - About the 'copyable' strings: if I am preparing a translation file for a language where a string is copyable, should this string not appear at all in the translated file of this same language if the translated text content is the same as the original english one?
>
> I'd strongly vote for the script not trying to be too smart. When a translation is by chance the same for some language, it should still appear in the language's translation file, since as a translator, I want to see the strings that end up in 'my' language because at some point in the future I might want to change it; so not seeing it is not very helpful, then I'll never find out that this string even exists.

Ok. Will do it this way.

> Same reasoning about the formats - I don't know how easy it is to check them but in my opinion it would also be quite okay to just have some other means of validating the whole translation - formats are just one caveat, special character or unescaped ampersands etc are others; so I'm not too conviced that this script should handle that but a 'linting' task that can be called by every translator would be very helpful since you want to call that lint at the end (just before committing) whereas you call the sync script at the beginning of a 'translation update session'.

About the formats, you said before that "if a fornat is translated but it contains format mistakes, it should not be copied to the new file. otherwise the mistake will not be fixed.

therefore it is important that the update script detects bad formats, and
replaces them with TODO."

I want to do exactly what you asked. My doubt is, inside this TODO that you mentioned, what text content should I include?

- the translated wrong one?
- the english correct one?
- both?
- something else?

**Comment by rsevero** [comment]
Ok.

I will try to work on this latter today.

------- Original Message -------

**Comment by marcocorvi** [comment]
On Tue, Jan 31, 2023, 2:47 PM Rodrigo Severo ***@***.***>
wrote:

> ------- Original Message -------
> On Tuesday, January 31st, 2023 at 10:30 AM, Matthias Keller ***@***.***>
> wrote:
>
> >> - About the 'copyable' strings: if I am preparing a translation file
> for a language where a string is copyable, should this string not appear at
> all in the translated file of this same language if the translated text
> content is the same as the original english one?
> >
> > I'd strongly vote for the script not trying to be too smart. When a
> translation is by chance the same for some language, it should still appear
> in the language's translation file, since as a translator, I want to see
> the strings that end up in 'my' language because at some point in the
> future I might want to change it; so not seeing it is not very helpful,
> then I'll never find out that this string even exists.
>
> Ok. Will do it this way.
>
> > Same reasoning about the formats - I don't know how easy it is to check
> them but in my opinion it would also be quite okay to just have some other
> means of validating the whole translation - formats are just one caveat,
> special character or unescaped ampersands etc are others; so I'm not too
> conviced that this script should handle that but a 'linting' task that can
> be called by every translator would be very helpful since you want to call
> that lint at the end (just before committing) whereas you call the sync
> script at the beginning of a 'translation update session'.
>
> About the formats, you said before that "if a fornat is translated but it
> contains format mistakes, it should not be copied to the new file.
> otherwise the mistake will not be fixed.
>
> therefore it is important that the update script detects bad formats, and
> replaces them with TODO."
>
> I want to do exactly what you asked. My doubt is, inside this TODO that
> you mentioned, what text content should I include?
>
> - the translated wrong one?
> - the english correct one?
> - both?
> - something else?
>

the current (correct) english text.
anything else is misleading.

it is  TODO.

**Comment by marcocorvi** [comment]
this issue is not outdated, therefore i close it

**Pull request closed without merging**
