### PR TITLE
Add .gitignore and delete local.properties

### PR DESCRIPTION
**Pull request by aljiru**
I recommend adding this gitignore so local configuration files remain on your local repository and not exposed to everyone on the remote repository

### CODE REVIEW

**Comment by Tapter** [comment]
Why not commit the .project/eclipse files? Like that everyone that uses eclipse can directly import the project? (dunno about the ant/local.properties)

**Comment by aljiru** [comment]
After reading (http://einverne.github.io/post/2016/04/should-i-git-ignore-project-file-under-eclipse.html) i agree it could be a good idea to keep this file so I've made the change.

**Comment by Tapter** [comment]
Thanks. However I'd propose to also keep the two files under .settings because they compliment the eclipse project setup by specifying project defaults that might not be set on every machine by default (UTF-8 and \n as linenedings isn't the OS-default on Windows). Removing this files leads to 'every' eclipse developer potentially having different settings

**Comment by aljiru** [comment]
Ok, now I understand. Then the proper way to solve this would be to configure Ant (build.xml) so when you import the project using ant (same with maven or gradle) to Eclipse (or IntelliJ or whatever) it handles those configurations properly so you don't have to rely on pushing platform configuration files to the remote repository (neither .project file). 
I'm not very used to Ant (I have a separated branch with gradle configuration) but possibly UTF-8 can be enforced using Ant (https://stackoverflow.com/questions/4211825/ant-encoding-problem-on-windows-utf-8-files-but-spits-garbage-on-diacritics/4581086).
So, as Ant is not configured to handle all these configurations I guess those files can't be deleted from the repo.

**Comment by Tapter** [comment]
How do you expect ant to handle that? You can probably configure ANT to use whatever encodings etc for the build. Those Files in the .settings though have the meaning of configuring the IDE on what to use. If your files aren't created in the right way by the IDE, ant cannot change this for you. You want to create the files right from the start, not adapt the compiler and every other system to various formats you might be producing.
You could make an ant target to GENERATE the project and settings files for your favorite IDE (that's what gradle's 'eclipse' plugin does - but then this functionality has to be included in the build tool and in the case of ANT you'd probably have to write it yourself which also isn't very convenient and only has the effect that .project files only appear when you use eclipse and .intelliJ or whatver files only appear if using intellij.... And in addition you'll have to run something first, before you ever see the project in the IDE (gradle can also make this easier because gradle projects can be detected automatically - but I don't know about ant)...

**Comment by aljiru** [comment]
Ok. So definitely is not a good idea to remove .settings folder.

**Pull request closed without merging**
