### PR TITLE
Portuguese translation: array.xml and plurals.xml

### PR DESCRIPTION
**Pull request by rsevero**
Including new translations in array and plurals xml files.

### CODE REVIEW

**Comment by marcocorvi** [comment]
thanks

**Comment by marcocorvi** [comment]
pt included in the apk.

there are errors:
1 string with no default
61 translated comments
4 bad formats

furthermore
19 copied strings not marked as copyable 
 usually these are NOT errors, but it is worth checking translations that are the same as english strings

**Comment by rsevero** [comment]
Which lint package do you use?

I can't find you that works with xml files.

------- Original Message -------

**Comment by marcocorvi** [comment]
the compiler gives warnings about no default translation.

clearly this is not an error.
just bloating the apk.

**Comment by rsevero** [comment]
Unfortunatelly I don't know how to call the compiler so I see these errors you listed.

If there are instructions somewhere on how to do it I can try to fix the errors myself.
------- Original Message -------

**Comment by marcocorvi** [comment]
i compile with ant (which calls helper programs and javac).
to make things even simpler i use make

maybe, there are howto for ant and studio on the app repo.

for ant it is just a matter to call it with one of the commands of the
default android ant build config file.
for studio you create a project and use the studio interface menus.

**Comment by marcocorvi** [comment]
i do not remember why the string "info_volume_value" with unicode is
commented.
maybe because i tried it (as the string should use unicode) but it did not
appear correctly on some device ...

i rename the unicode string appending something so that strings are unique,
and change the comment in the default file

**Comment by rsevero** [comment]
------- Original Message -------
On Monday, January 30th, 2023 at 1:56 PM, marco corvi ***@***.***> wrote:

> i do not remember why the string "info_volume_value" with unicode is
> commented.
> maybe because i tried it (as the string should use unicode) but it did not
> appear correctly on some device ...
>
> i rename the unicode string appending something so that strings are unique,
>
> and change the comment in the default file

Great!Message ID: ***@***.***>

>

**Pull request merged**
