### PR TITLE
strings_update.pl: all tags included in commented lines in EN are passed to NEW

### PR DESCRIPTION
**Pull request by rsevero**
Created function to parse xml lines to make it easier to deal with tagged comments.

Now all tags included in commented lines in EN are passed to NEW.

Used a little bit more of Perlish code...

### CODE REVIEW

**Comment by marcocorvi** [comment]
at this point it should be easy to detect a format (search '%1$') and check
format correctness (number of args and their types).

or this can be left to lint since there may be only a few bad formats.

**Comment by rsevero** [comment]
You mean include some extra checks in strings_update? Yes, that's entirely possible for sure.

Please let me know what would these new checks be exactly if you really believe they should be done in strings_update and not lint.

**Comment by marcocorvi** [comment]
format errors can crash the app.
it would be good to detect them.

errors can arise from mismatch of number and types of args in the format.

a format can have error if the english format was changed after the
translation got dropped.
therefore there can be a format error in old translated strings.

it is probably better to have a separate format check script.

however format errors can be expected to be very few, therefore it is
enough to check lint output.

**Comment by rsevero** [comment]
I would like to suggest to you that the translation files (at least strings.xml) be constantly kept up to date with all the necessary TODOs.

I say this from the perspective of a translation manager. It's way easier to understand and do the task at hand having the relevant strings.xml file complete with all necessary TODOs.

With the newer strings_update.pl file it's easy to do it automatically. I can write a script for that if you want.

Please let me know what you think so I can act accordinly.

**Comment by marcocorvi** [comment]
the problem with translation that have many TODO is the number or missing
translations reported by automatic tools.
that is why i move them out of the build tree.

another issue is that there is no point that i manually fill unmaintained
translations.

if the string-update script is reliable ( works on strings array and
plurals and manages multiline strings ) i will add a make command that sync
the translation folders. :-D

in any case i would update only maintained translations.
if a stale translation is picked up it can be sync-ed with the script.

**Pull request merged**
